[build-system]
build-backend = "uv_build"
requires = ["uv-build>=0.12.1,<0.13.0"]

[project]
name = "hymns"
version = "2026.7.0"
description = "Compile a single PDF containing all the hymns in the collection \"Hymns for Home and Church\""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "pymupdf>=1.28.0",
    "pypng>=0.20220715.0",
    "qrcode>=8.2",
]

[project.urls]
"Homepage" = "https://github.com/williamjacksn/hymns"
"Issues" = "https://github.com/williamjacksn/hymns/issues"

[project.scripts]
gen-all-hymns = "hymns:gen_all"
hymns = "hymns:main"

[dependency-groups]
dev = [
    "ruff>=0.16.5",
    "ty>=0.0.65",
    "uv-build>=0.12.1",
]

[tool.ruff.lint]
extend-select = ["ANN", "E", "F", "FURB", "I", "PERF", "Q", "RSE", "RUF", "S", "UP"]
